application: app-assignment-four
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /templates/css
  static_dir: templates/css
- url: /templates/js
  static_dir: templates/js
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest